import { VocabularyWord } from "./types";

export const DEFAULT_WORDS: VocabularyWord[] = [
  {
    id: "w1",
    word: "ambition",
    phonetic: "/æmˈbɪʃ.ən/",
    translation: "n. 抱负，雄心，野心",
    sentence: "His ambition is to create tools that make education accessible to all.",
    sentenceTranslation: "他的抱负是创造能让所有人都能接受教育的工具。",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 5, // 5 days ago
  },
  {
    id: "w2",
    word: "benevolent",
    phonetic: "/bəˈnev.əl.ənt/",
    translation: "adj. 仁慈的，善意的，慈善的",
    sentence: "The benevolent teacher took extra time to guide struggling students.",
    sentenceTranslation: "这位仁慈的老师花额外的时间辅导有困难的学生。",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 4,
  },
  {
    id: "w3",
    word: "diligent",
    phonetic: "/ˈdɪl.ɪ.dʒənt/",
    translation: "adj. 勤勉的，勤奋的, 孜孜不倦的",
    sentence: "Through diligent practice, she mastered the complex piano concerto.",
    sentenceTranslation: "通过勤奋练习，她掌握了那首复杂的钢琴协奏曲。",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 3,
  },
  {
    id: "w4",
    word: "enthusiasm",
    phonetic: "/ɪnˈθjuː.zi.æz.əm/",
    translation: "n. 热情，热心，热忱",
    sentence: "The children played in the snow with great enthusiasm and laughter.",
    sentenceTranslation: "孩子们带着极大的热情和欢笑在雪地里玩耍。",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 2,
  },
  {
    id: "w5",
    word: "foster",
    phonetic: "/ˈfɒs.tər/",
    translation: "v. 培养，促进，抚育",
    sentence: "We strive to foster a creative environment where mistakes are seen as learning steps.",
    sentenceTranslation: "我们努力营造一个富有创造力的环境，在这里，错误被视为学习的台阶。",
    createdAt: Date.now() - 1000 * 60 * 60 * 24 * 1,
  },
  {
    id: "w6",
    word: "genuine",
    phonetic: "/ˈdʒen.ju.ɪn/",
    translation: "adj. 真实的，真诚的，真正的",
    sentence: "Her response carried a genuine warmth that made everyone feel safe.",
    sentenceTranslation: "她的回答带着真诚的温暖，让每个人都感到安心。",
    createdAt: Date.now() - 1000 * 60 * 50,
  },
  {
    id: "w7",
    word: "harmony",
    phonetic: "/ˈhɑː.mə.ni/",
    translation: "n. 和谐，融洽，和声",
    sentence: "People from different cultures should strive to live in peace and harmony.",
    sentenceTranslation: "来自不同文化背景的人们应该努力和平与和谐地生活。",
    createdAt: Date.now() - 1000 * 60 * 40,
  },
  {
    id: "w8",
    word: "influence",
    phonetic: "/ˈɪn.flu.əns/",
    translation: "n. 影响，作用 v. 影响，感化",
    sentence: "Good literature has a deep influence on how we view the human experience.",
    sentenceTranslation: "优秀的文学作品对我们如何看待人类经历有着深远的影响。",
    createdAt: Date.now() - 1000 * 60 * 30,
  },
  {
    id: "w9",
    word: "journey",
    phonetic: "/ˈdʒɜː.ni/",
    translation: "n. 旅行，旅程 v. 旅行，旅途",
    sentence: "Embracing self-improvement is a long but rewarding journey.",
    sentenceTranslation: "拥抱自我提升是一段漫长但值得的旅途。",
    createdAt: Date.now() - 1000 * 60 * 20,
  },
  {
    id: "w10",
    word: "persistence",
    phonetic: "/pəˈsɪs.təns/",
    translation: "n. 坚持不懈，执着，持续",
    sentence: "Her persistence finally paid off when she solved the mysterious bug.",
    sentenceTranslation: "当她最终解决那个神秘的漏洞时，她的坚持终于得到了回报。",
    createdAt: Date.now() - 1000 * 60 * 10,
  },
];
